---
- name: Deploy docker-compose.yaml
  hosts: Debian
  become: True

  vars: 
    path: /root
    path_script: /etc/ansible/zabbix-server-in-dockers/ansible
    path_copy_docker_compose: /etc/ansible/zabbix-server-in-dockers

  tasks: 
    - name: Copy docker-compose.yaml
      copy:
        src: "{{ path_copy_docker_compose }}/docker-compose.yaml"
        dest: "{{ path }}"

    - name: Run docker-compose
      script: "{{ path_script }}/docker_compose_up.sh"

    - name: Check docker ps
      command: bash -c "docker ps"
      register: output

    - name: Show docker ps
      debug: 
        var: output
